# Generated by Django 3.0.3 on 2020-02-28 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casenumber', models.CharField(max_length=100, verbose_name='案號')),
                ('address', models.CharField(max_length=100, verbose_name='住址')),
                ('auctionday', models.DateField(default=datetime.date.today, verbose_name='拍賣日')),
                ('auctionlevel', models.CharField(max_length=5, verbose_name='拍賣次數')),
                ('floorprice', models.IntegerField(verbose_name='底價')),
                ('margin', models.IntegerField(verbose_name='保証金')),
                ('creditor', models.CharField(max_length=100, verbose_name='債務人')),
                ('debtor', models.CharField(max_length=100, verbose_name='債權人')),
            ],
        ),
    ]
