# Generated by Django 3.0.3 on 2020-03-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildnumber', models.CharField(blank=True, max_length=100, null=True)),
                ('buildarea', models.DecimalField(decimal_places=2, max_digits=6)),
                ('buildurl', models.CharField(blank=True, max_length=255, null=True)),
                ('buildholdingpointperson', models.PositiveIntegerField()),
                ('buildholdingpointall', models.PositiveIntegerField()),
                ('buildtype', models.CharField(blank=True, choices=[('1公寓(5樓含以下無電梯)', '1公寓(5樓含以下無電梯)'), ('2透天厝', '2透天厝'), ('3店面(店舖)', '3店面(店舖)'), ('4辦公商業大樓', '4辦公商業大樓'), ('5住宅大樓(11層含以上有電梯)', '5住宅大樓(11層含以上有電梯)'), ('6華廈(10層含以下有電梯)', '6華廈(10層含以下有電梯)'), ('7套房(1房(1廳)1衛)', '7套房(1房(1廳)1衛)'), ('8工廠', '8工廠'), ('9廠辦', '9廠辦'), ('10農舍', '10農舍'), ('11倉庫', '11倉庫'), ('Z其他等型態', 'Z其他等型態')], max_length=50, null=True)),
                ('usearea', models.CharField(blank=True, choices=[('第一種住宅區', '第一種住宅區'), ('第二種住宅區', '第二種住宅區'), ('第三種住宅區', '第三種住宅區'), ('第四種住宅區', '第四種住宅區'), ('第一種商業區', '第一種商業區'), ('第二種商業區', '第二種商業區'), ('第三種商業區', '第三種商業區'), ('第四種商業區', '第四種商業區'), ('第二種工業區', '第二種工業區')], max_length=20, null=True)),
                ('postmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.PostModel')),
            ],
        ),
    ]
