# Generated by Django 3.0.3 on 2020-03-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_buildmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='auctionlevel',
            field=models.CharField(choices=[('第一拍', '第一拍'), ('第二拍', '第二拍'), ('第三拍', '第三拍'), ('第四拍', '第四拍')], max_length=5, verbose_name='拍賣次數'),
        ),
    ]
